# Generated by Django 4.1.7 on 2023-03-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0002_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
