# Generated by Django 4.1.7 on 2023-03-01 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0003_itemcategory_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=55)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('del_price', models.IntegerField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, max_length=500, null=True)),
                ('img_item', models.ImageField(blank=True, max_length=55, null=True, upload_to='')),
                ('item_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemtype')),
                ('prduct_cetegory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcategory')),
            ],
        ),
    ]
