# Generated by Django 4.1.7 on 2023-03-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0004_itemtype_itemproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_item', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='itemcategory',
            old_name='item_category',
            new_name='category_item',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='del_price',
            new_name='price_del',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='item_type',
            new_name='type_item',
        ),
        migrations.RenameField(
            model_name='itemtype',
            old_name='item_type',
            new_name='type_item',
        ),
        migrations.RemoveField(
            model_name='itemproduct',
            name='prduct_cetegory',
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='category_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='dosage_item',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='company_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcompany'),
        ),
    ]
