# Generated by Django 4.1.7 on 2023-03-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0005_itemcompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproduct',
            name='size_item',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
