# Generated by Django 4.1.7 on 2023-03-01 09:46

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0006_itemproduct_size_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uint_item', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='unit_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.fields.CharField, to='app_items.itemuint'),
        ),
    ]
