# Generated by Django 4.1.7 on 2023-03-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0007_itemuint_itemproduct_unit_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='company_item',
            field=models.ForeignKey(blank=True, default='img_coming_soom.jpg', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcompany'),
        ),
    ]
