# Generated by Django 4.1.7 on 2023-03-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0008_alter_itemproduct_company_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='company_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcompany'),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='img_item',
            field=models.ImageField(blank=True, default='img_coming_soom.jpg', max_length=55, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='price_del',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
