# Generated by Django 4.1.7 on 2023-03-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0009_alter_itemproduct_company_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproduct',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
