# Generated by Django 4.1.7 on 2023-03-13 08:35

import app_items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0010_itemproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='category_item',
            field=models.SlugField(blank=True, null=True, verbose_name=app_items.models.ItemCategory),
        ),
    ]
