# Generated by Django 4.1.7 on 2023-03-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0012_alter_itemproduct_category_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_items.itemcategory'),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='category_item',
            field=models.CharField(blank=True, choices=[('tablet and capsules', 'Tablet And Capsules'), ('syrub', 'Syrub'), ('solution', 'Solution'), ('powder', 'Powder'), ('injection', 'Injection'), ('infution', 'Infution'), ('oder', 'Oder')], default='oder', max_length=55, null=True),
        ),
    ]
