# Generated by Django 4.1.7 on 2023-03-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_items', '0013_itemproduct_category_alter_itemproduct_category_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='category_item',
            new_name='category',
        ),
    ]
